---
macos_defaults:
  - name: Disable prompting to use new exteral drives as Time Machine volume
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: 'true'

  - name: Quit printer app after print jobs complete
    domain: com.apple.print.PrintingPrefs
    key: Quit When Finished
    type: bool
    value: 'true'

  - name: Show filename extensions by default
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: 'true'

  - name: Disable creation of .DS_Store files on network volumes
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: 'true'

  - name: Finder show all files
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: 'true'

  - name: Hide external hard drives on desktop
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: 'false'

  - name: Hide hard drives on desktop
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: 'false'

  - name: Hide removable media on desktop
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: 'false'

  - name: Hide mounted servers on desktop
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: 'false'

  - name: Hide icons on desktop
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: 'false'

  - name: Enable status bar in Finder
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: 'true'

  - name: Enable breadcrumbs in Finder
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: 'true'

  - name: Disable Trash empty warning
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: 'false'

  - name: Disable file extension change warning
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: 'false'

  - name: Set default Finder view to list
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv

  - name: Set default Finder new window target
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfLo

  - name: Set default Finder location to ~/Downloads
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: file://{{ ansible_user_dir }}/Downloads/

  - name: Auto-hide the Dock
    domain: com.apple.dock
    key: autohide
    type: bool
    value: 'true'

  - name: Disable recent apps in the Dock
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: 'false'

  - name: Disable icon bouncing in the Dock
    domain: com.apple.dock
    key: no-bouncing
    type: bool
    value: 'true'

  - name: Change minimize effect
    domain: com.apple.dock
    key: mineffect
    type: string
    value: scale

  - name: Disable minimize to app effect
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: 'false'

  - name: Show app switcher on all displays
    domain: com.apple.dock
    key: appswitcher-all-displays
    type: bool
    value: 'true'

  - name: Set small Dock size
    domain: com.apple.dock
    key: tilesize
    type: int
    value: '1'

  - name: Remove all dock icons
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: '[]'

  - name: Pin dock to the right
    domain: com.apple.dock
    key: orientation
    type: string
    value: right

  - name: Prevent switching desktops automatically
    domain: com.apple.dock
    key: workspaces-auto-swoosh
    type: bool
    value: 'false'

  - name: Save screenshots to ~/Downloads
    domain: com.apple.screencapture
    key: location
    value: '{{ ansible_user_dir }}/Downloads'

  - name: Set expose hot corner bottom-left
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: '0'

  - name: Set expose hot corner bottom-left modifier
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: '0'

  - name: Set expose hot corner bottom-right
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: '0'

  - name: Set expose hot corner bottom-right modifier
    domain: com.apple.dock
    key: wvous-br-modifier
    type: int
    value: '0'

  - name: Set expose hot corner top-left
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: '0'

  - name: Set expose hot corner top-left modifier
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: '0'

  - name: Set expose hot corner top-right
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: '0'

  - name: Set expose hot corner top-right modifier
    domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: '0'

  - name: Disable automatically rearranging Spaces
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: 'false'

  - name: Enable grouping windows by application
    domain: com.apple.dock
    key: expose-group-apps
    type: bool
    value: 'false'

  - name: Set screensaver timeout
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: '600'

  - name: Set screensaver password timeout
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: '1'

  - name: Set screensaver password delay
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: '5'

  - name: Configure bluetooth Apple trackpad - tap-to-click
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: '1'

  - name: Configure bluetooth Apple trackpad - 2 finger tap right-click
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: trackpadRightClick
    type: int
    value: '1'

  - name: Configure bluetooth Apple trackpad - pinch to zoom
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: trackpadPinch
    type: int
    value: '1'

  - name: Configure bluetooth Apple trackpad - 2 finger rotate
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: trackpadRotate
    type: int
    value: '1'

  - name: Configure bluetooth Apple trackpad - 3 finger swipe between pages
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerHorizSwipeGesture
    type: int
    value: '1'

  - name: Configure bluetooth Apple trackpad - smart zoom
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: trackpadTwoFingerDoubleTapGesture
    type: int
    value: '1'

  - name: Configure bluetooth Apple trackpad - Notification Center
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadTwoFingerFromRightEdgeSwipeGesture
    type: int
    value: '3'

  - name: Configure bluetooth Apple trackpad - perform look up
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: trackpadThreeFingerTapGesture
    type: int
    value: '2'

  - name: Configure builtin Apple trackpad - tap-to-click
    domain: com.apple.AppleMultitouchtrackpad
    key: Clicking
    type: int
    value: '1'

  - name: Configure builtin Apple trackpad - 2 finger tap right-click
    domain: com.apple.AppleMultitouchtrackpad
    key: trackpadRightClick
    type: int
    value: '1'

  - name: Configure builtin Apple trackpad - pinch to zoom
    domain: com.apple.AppleMultitouchtrackpad
    key: trackpadPinch
    type: int
    value: '1'

  - name: Configure builtin Apple trackpad - 2 finger rotate
    domain: com.apple.AppleMultitouchtrackpad
    key: trackpadRotate
    type: int
    value: '1'

  - name: Configure builtin Apple trackpad - 3 finger swipe between desktops
    domain: com.apple.AppleMultitouchtrackpad
    key: TrackpadThreeFingerHorizSwipeGesture
    type: int
    value: '2'

  - name: Configure builtin Apple trackpad - smart zoom
    domain: com.apple.AppleMultitouchtrackpad
    key: trackpadTwoFingerDoubleTapGesture
    type: int
    value: '1'

  - name: Configure builtin Apple trackpad - Notification Center
    domain: com.apple.AppleMultitouchtrackpad
    key: TrackpadTwoFingerFromRightEdgeSwipeGesture
    type: int
    value: '3'

  - name: Configure builtin Apple trackpad - perform look up
    domain: com.apple.AppleMultitouchtrackpad
    key: trackpadThreeFingerTapGesture
    type: int
    value: '2'

  - name: Enable tap-to-click on Apple mouse
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: '1'

  - name: Set global two finger horizontal swipe between pages
    domain: NSGlobalDomain
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: 'true'

  - name: Set key repeat rate (1)
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: '15'

  - name: Set key repeat rate (2)
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: '2'

  - name: Check for software updates daily
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: '1'

  - name: Expand save panel 1 by default
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: 'true'

  - name: Expand save panel 2 by default
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: 'true'

  - name: Expand print panel 1 by default
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: 'true'

  - name: Expand print panel 2 by default
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: 'true'

  - name: Set dark theme
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: 'Dark'

  - name: Enable Tab in modal dialogs
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: '3'

  - name: Allow apps from devs
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: 'false'


macos_defaults_xml:
  - key: com.apple.symbolichotkeys
    filename: mac_shortcuts

  - key: com.apple.controlcenter
    filename: mac_controlcenter

  - key: com.dshnkao.SpaceId
    filename: spaceid
