---
- name: Register Brewfile
  stat:
    path: "{{ brewfile_dir }}/Brewfile"
  register: brew_file

- block:
    - name: Check if install is needed
      command: "{{ homebrew_brew_bin_path }}/brew bundle check chdir={{ brewfile_dir }}"
      register: brew_check
      changed_when: false
      failed_when: false

    - name: Install with passowrdless sudo
      block:
        - name: allow passwordless sudo
          lineinfile:
            path: /etc/sudoers
            line: 'ALL ALL=(ALL) NOPASSWD: ALL'
          become: true

        - name: Install from Brewfile
          command: "{{ homebrew_brew_bin_path }}/brew bundle --no-lock chdir={{ brewfile_dir }} "
          async: 100000
          poll: 5

      always:
        - name: disable passwordless sudo
          lineinfile:
            path: /etc/sudoers
            line: 'ALL ALL=(ALL) NOPASSWD: ALL'
            state: absent
          become: true
      when: brew_check.rc == 1
  when: brew_file.stat.exists

- name: Update all homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
